name: Update Game Results

on:
  schedule:
    # Run every 3 hours (UTC)
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the update script
      - name: Run update script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} # Add your MongoDB URI to GitHub Secrets
        run: python update_results.py
